// <auto-generated />
namespace GPSTracking.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Login_Registration_AddVehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Login_Registration_AddVehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "201409211315028_Login_Registration_AddVehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
