// <auto-generated />
namespace GPSTracking.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changesset16 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesset16));
        
        string IMigrationMetadata.Id
        {
            get { return "201506021424023_changesset-16"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
